### ISSUE TITLE
Feature request. Add checks for ingresses without Services.

### ISSUE THREAD

**Issue by kirill-korzun** [emirozer/kubectl-doctor#2]
Hi Emir,

This is pretty much a feature request rather than a bug; In our current environment we have a few dev clusters getting constant creation/deletion requests, and our CI isn't perfect, so time to time we face situation when we have a bunch of automatically created ingress objects being pointed to Service object don't exist anymore.

I'm just wondering if you can add such case to your sanity check steps and display/auto-delete ingress objects?

**Comment by emirozer** [comment]
great idea 👍

**Comment by emirozer** [comment]
note to self: 

ingresses, err := kubeCli.NetworkingV1beta1().Ingresses(namespace).List(v1.ListOptions{})

packs a 404 in err.

**Comment by emirozer** [comment]
https://github.com/emirozer/kubectl-doctor/releases/tag/0.3.0
