### ISSUE TITLE
Doesn't handle multipule kube-config files

### ISSUE THREAD

**Issue by switchboardOp** [emirozer/kubectl-doctor#3]
I work with more than one cluster, so I set the `KUBECONFIG` environment variable to list of paths to configuration files as described [here](https://kubernetes.io/docs/tasks/access-application-cluster/configure-access-multiple-clusters/#set-the-kubeconfig-environment-variable).

This causes `doctor` to panic.
```text
panic: stat /Users/me/.kube/config:/Users/me/.kube/mini-kube-config:/Users/me/.kube/dev-kube-config:/Users/me/.kube/prod-kube-config: no such file or directory

goroutine 1 [running]:
github.com/emirozer/kubectl-doctor/pkg/client.tryGetKubeConfigFromEnvVar(0x50, 0xc0002c4e60, 0x1ebccc0)
	/Users/eoz/go/src/github.com/emirozer/kubectl-doctor/pkg/client/client.go:66 +0x14d
github.com/emirozer/kubectl-doctor/pkg/client.InitClient(0xc0000b00c0)
	/Users/eoz/go/src/github.com/emirozer/kubectl-doctor/pkg/client/client.go:32 +0x34
github.com/emirozer/kubectl-doctor/pkg/plugin.init.0()
	/Users/eoz/go/src/github.com/emirozer/kubectl-doctor/pkg/plugin/cmd.go:45 +0x97
```

`doctor` should respect the merged config and the current context.

**Comment by emirozer** [comment]
Thanks for the report, you are right i didn't handle that case yet, will fix quite soon.

**Comment by emirozer** [comment]
Sorry for the late update...

https://github.com/emirozer/kubectl-doctor/commit/dffa19a7c7bd1663e6c4c6c3389dc89743aa121c

will adress your issue and it is going in the next release

**Comment by emirozer** [comment]
https://github.com/emirozer/kubectl-doctor/releases/tag/0.3.0

I think i tested with enough scenarios, just in case if it is still troublesome for you feel free to reopen!
